# remote_theme: benbalter/retlab
remote_theme:  oinam/oinam-jekyll
plugins:
  - jekyll-remote-theme
title: Managing Software Development Body of Knowledge
description: Review of the research in software development management


collections:
  people:
    output: true