# remote_theme: benbalter/retlab
# remote_theme:  oinam/oinam-jekyll
# remote_theme:  daattali/beautiful-jekyll@6.0.1
remote_theme:  mmistakes/so-simple-theme@3.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-scholar
title: Managing Software Development Body of Knowledge
description: Review of the research in software development management


collections:
  people:
    output: true
  process:
    output: true
  scope:
    output: true
  planning:
    output: true